services:
  ustro-share:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - TRUST_PROXY=true # Important : ton dédié est en front, donc il faut faire confiance au proxy
      # Remplace les IP par l'adresse IP privée de ton dédié (Wireguard) ou son IP publique
      - DATABASE_URL=postgresql://shareustro:s54sD7fAyhNcsENX@10.66.66.5:5432/shareustro?schema=public
      - REDIS_URL=redis://maWvMElNOkST1CcI@10.66.66.5:6379/10
      # Si tu as un conteneur ClamAV sur le dédié, pointe vers lui ici
      #- CLAMAV_HOST=10.66.66.5
      #- CLAMAV_PORT=3310
    volumes:
      - "./data:/opt/app/backend/data"
      - "./data/images:/opt/app/frontend/public/img"
